### ISSUE TITLE
Which browsers are supported

### ISSUE THREAD

**Issue by drnkwati** [jaysonwm/popupmodal.js#1]
Hi
I wish to know which browsers are supported without polyfills
thanks

**Comment by jaysonwm** [comment]
Hi @drnkwati,

You can refer to [https://caniuse.com/#search=es6](url).
By the way, this plugin is not actively maintained anymore. :(

**Comment by drnkwati** [comment]
It's a shame
no one got to use it.
By the way going to caniuse.com does not answer my question at all.
You must be specific  about which es6 features were used for those who wish to poly-fill
